language: node_js
node_js:
    - "lts/*"

install:
    - npm install
script:
    - npm run build
cache:
    directories:
        - "node_modules"
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/id_rsa
- curl --ftp-create-dirs
       -T dist
       --key /tmp/id_rsa
       sftp://${DEPLOY_USER}@${DEPLOY_URL}