language: node_js
node_js:
    - "lts/*"

install:
    - npm install
script:
    - npm run build
cache:
    directories:
        - "node_modules"
after_success:
- find dest -type f -exec curl --ftp-create-dirs --u ${DEPLOY_USER}:${DEPLOY_PASSWORD} -T {} ftp://${DEPLOY_URL} {} \;