language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: "<deploy-host>"
install:
- npm install
script:
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_0184aa3b45b2_key -iv $encrypted_0184aa3b45b2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist {$DEPLOY_USER}@{$DEPLOY_URL}:{$DEPLOY_PATH}
  on:
    branch: master
